### ISSUE TITLE
Number of Submitters

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#121]
Matt Sorenson: Does OGC policy recommend or require multiple submitters (at least three)? More people supported drafting this and should be listed/credited.

**Comment by jyutzler** [comment]
Recommend asking SWG members over email whether they wish to be added as contributors then closing this issue. Also I think the Core and Collections labels are wrong.

**Comment by joanma747** [comment]
Harrison, Jeffrey G CIV (US) <Jeffrey.G.Harrison@usace.army.mil>Dl. 28/9/2020 15:08
I would like to be a Submitter please!
Thanks and Regards,
Jeff

**Comment by jerstlouis** [comment]
I would also like to be a submitter please.
Thank you.
-Jerome

**Comment by joanma747** [comment]
I would like to be a submitter too: Joan  Masó, UAB-CREAF

**Comment by dblodgett-usgs** [comment]
Yes. David Blodgett, U.S. Geological Survey

**Comment by geomancer2012** [comment]
An "API Common" is a necessity.

**Comment by joanma747** [comment]
De: Sullivan, Donald V. (ARC-SGE) <donald.v.sullivan@nasa.gov>
Enviat el: dilluns, 23 de novembre de 2020 20:40

Please add me (NASA) to the list. Thank you,
Don

**Comment by chris-little** [comment]
@joanma747 Please add me (Met Office) too. Chris

**Comment by fhoubie** [comment]
@joanma747  Joan, please add me as well (Frédéric Houbie - Hexagon). Thanks

**Comment by cmheazel** [comment]
I have added you all as individual submitters and as submitting organizations. If this is not correct please let me know.

**Comment by cportele** [comment]
@cmheazel - add me and interactive instruments as submitters, too.

**Comment by cmheazel** [comment]
Everyone who has indicated that their organization is a submitting organization has been added to the submitters list and their organization added to the list of submitting organizations.

**Comment by jerstlouis** [comment]
@cmheazel I don't see Clemens yet on
https://github.com/opengeospatial/ogcapi-common/blob/master/core/clause_1_front_material.adoc

**Comment by cportele** [comment]
Thanks @jerstlouis. 
@cmheazel - I have created a PR: https://github.com/opengeospatial/ogcapi-common/pull/207.
