### ISSUE TITLE
/req/core/query-param-unknown is too strict

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-common#131]
The latest April-2020-Updates draft of 20-024 states the following for Requirement 15:

"The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that is not specified in the API definition."

This requirement is too strict.  It requires clients to fully parse and grok the server's API definition, which will likely be beyond the capability of most clients.  Many clients will likely take the approach of determining the capabilities of a server by arming themselves with knowledge of the specifications and crawling through the relevant resources of the server starting at its OGC API landing page.

Not all optional query parameters defined in the specifications are required to be implemented by a server.  (At least I assume and hope that this is the case.)  A client may choose to send such a parameter to the server with the expectation that if it's not supported it'll simply be ignored.  This could happen if, e.g., the parameter is irrelevant to the server, or perhaps it was introduced in a revision of a specification that the server doesn't support and therefore isn't even aware of. 

The server may also choose to implement unadvertised vendor-specific query parameters.  I don't think this should be forbidden.

This approach of simply ignoring unsupported or unrecognized query parameters is the way classic the OGC web services work, and it has proven to be very useful in a multi-vendor environment where the clients and servers work on a best-effort basis.

**Comment by cmheazel** [comment]
@pomakis I have to agree.  

The question arises, what do we do if a server implements a parameter which is defined in the standard, does not advertise that parameter, and implements it incorrectly? How do we detect that the server is not conformant to the Standard?

The current approach is draconian. All parameters shall be advertised and all parameters shall be conformant. It does the job but is also a bit unrealistic.

Open to suggestions.

**Comment by cportele** [comment]
Here is the discussion that resulted in the current approach: https://github.com/opengeospatial/ogcapi-features/issues/128. I do not see how this could change as long as OpenAPI is used.

**Comment by jerstlouis** [comment]
As per the discussion in #131, I do not think this issue can be closed yet.

**Comment by joanma747** [comment]
An example of the behavior of using extra parameter:
Take this:
http://geoserveis.icgc.cat/icc_mapesbase/wms/service?REQUEST=GetMap&VERSION=1.1.0&SERVICE=WMS&SRS=EPSG:25831&BBOX=290368.84,4543236.42,292203.28,4545070.86&WIDTH=520&HEIGHT=520&LAYERS=orto25c&STYLES=&FORMAT=image/jpeg&BGCOLOR=0xFFFFFF&TRANSPARENT=TRUE&EXCEPTION=INIMAGE
Replace the GetMap with GetCapabilities and it works!
http://geoserveis.icgc.cat/icc_mapesbase/wms/service?REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WMS&SRS=EPSG:25831&BBOX=290368.84,4543236.42,292203.28,4545070.86&WIDTH=520&HEIGHT=520&LAYERS=orto25c&STYLES=&FORMAT=image/jpeg&BGCOLOR=0xFFFFFF&TRANSPARENT=TRUE&EXCEPTION=INIMAGE

Examples where 400 has some usefulness:
* Since OpenAPI is case sensible, wrong casing will generate a mistake
* Better caching
* Let know that you might be sending a parameter that you believe has "effect" but it does not.

There is a way in OpenAPI to support "additionalParameter"

**Comment by cmheazel** [comment]
Put on the agenda for the membership meeting. Review the history and try to summarize in a set of slides.

**Comment by cmheazel** [comment]
Suggestion:
1) Clients SHALL demonstrate that they format parameters as specified (strict conformance)
2) Servers SHALL demonstrate that they correctly process correctly formatted parameters (strict conformance)
3) Servers MAY also accept variations of the correct formatting of a parameter. (loose conformance)
This will allow a server implementation to attempt to interpret the meaning of mall-formed parameters while not imposing this level of service on all implementations. Clients must be able to build properly formatted parameters since they cannot count on all services to be forgiving.

**Comment by pomakis** [comment]
Yes, absolutely!

In fact, I've always been of the opinion that a service specification should never dictate what a server should not accept.  It should define endpoints, operations and parameters, and the required effects of those endpoints, operations and parameters.  Anything outside of this should be considered undefined behaviour.  This allows a server to provide vendor-specific extensions (the existence of which can be determined in a vendor-specific way), and also to be friendly and flexible when client applications (or people) produce requests that are not squeaky clean.

**Comment by cportele** [comment]
I am not able to join the meeting today, but a couple of comments:

* My [earlier comment](https://github.com/opengeospatial/oapi_common/issues/131#issuecomment-618196520) still applies.
* I do not remember that any interoperability issues have been raised with respect to the current approach from implementations over the last two years. And if an implementation wants to allow undocumented query parameters it can do so.
* If it is the idea to start capturing client requirements, this would have to go to a new requirements class with the appropriate standardization target type.

**Comment by cmheazel** [comment]
Check against Part 1 requirement 4 - does this impact core?

**Comment by joanma747** [comment]
There are 2 use cases for "non listed parameters":

* Capitalization
* Vendor specify parameters. OGC API Features mandates that Vendor specify parameters are added to the OpenAPI document: "Req 8: The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that is not specified in the API definition." (http://docs.opengeospatial.org/DRAFTS/17-069r4.html#query_parameters)

We are look at https://en.wikipedia.org/wiki/HTTP_302 as a way to redirect the URL with a "bad-spelled" parameter to a URL with the "corrected-spelled" parameter.

We will continue trying to use the Features approach and add a permission to allow for variations (being careful with the wording and ensure that the permission do not contradict the requirement). 

This is what was discussed in 2020-11-23 and we will revisit the issue next week.

**Comment by jerstlouis** [comment]
I suggest: "SHALL respond with a the status code 400, or a 302 relocation to a corrected URL if the server auto-corrected a request (e.g. in the case of wrong capitalization)".

For vendor-specific parameters, adding them to the OpenAPI definition makes sense.

Adding wildcard additional parameters though I feel is confusing for a client relying on the OpenAPI document. It is not something that a server wishing to provide a clear and precise description of its API would be happy to do in order to be able to be friendly to almost-right client requests.

**Comment by pomakis** [comment]
A 302 relocation would kinda require the server to analyze and correct all of the parameters rather than just stopping at the first one that it sees is not the proper case.  Otherwise, for example, a request that comes in whose parameters are all (technically incorrectly) init-caps, e.g.,

```
  https://...?Param1=a&Param2=b&Param3=c&Param4=d
```

would be redirected to:

```
  https://...?param1=a&Param2=b&Param3=c&Param4=d
```

would be redirected to:

```
  https://...?param1=a&Param2=b&Param3=c&Param4=d
```

would be redirected to:

```
  https://...?param1=a&param2=b&Param3=c&Param4=d
```

would be redirected to:

```
  https://...?param1=a&param2=b&param3=c&Param4=d
```

would be redirected to:

```
  https://...?param1=a&param2=b&param3=c&param4=d
```

This puts even more of a burden on a server.  I really don't see the harm in just allowing a server to accept parameters case-insensitively if it's confident of the client's intent.

Also, it can be quite onerous for a server to detect request parameters that aren't recognized.  An endpoint handler may pass through several different modules, each which picks out and handles parameters that are appropriate for that module.  For example, an authentication module might pick out and handle an "api_key" parameter, and a JSON-generation module might pick out and handle a "pretty=true" parameter.  There's not necessarily a single module that accepts all of the parameters at once and that authoritatively knows the complete set of accepted parameters.  As a server implementer, I don't want to spend my time writing a whole new software subsystem to deal with this, especially if it's to resolve something that I don't perceive to be a problem in the first place.

BTW, in JSON schema (according to https://json-schema.org/understanding-json-schema/reference/object.html), the default value of "additionalProperties" is true.  So an OpenAPI document needs extra verbiage to state that unlisted properties will be rejected with an error.

**Comment by cmheazel** [comment]
The query parameter validation section has been re-written. Two key points:
1) query parameter validation depends on the data model and content of the API definition document
2) we should allow an API to correct minor errors
I believe the updates address the issues raised above and is also testable.  
Comments welcome.

**Comment by pomakis** [comment]
I think these requirements are overly complicated and unnecessary.  While they may provide comfortable rigidity for the test suites, I don't see them providing any value to either servers or clients.  All they do (from my perspective as a service implementer) is significantly complicate the implementation effort.

Going out on a limb, this is what I think would make the most sense to say:

> If a query parameter of a request is defined in one or more of the OGC API standards, then its implementation must comply to those standards, and is subject to testing by the test suites of those standards. 
> 
> If a query parameter of a request is not defined in any of OGC API standards, then its behaviour is undefined with respect to the standards, regardless as to whether or not it's listed in the server's API definition.  The server may utilize this allowance to:
>   - accept alternate capitalizations, spellings, and/or aliases of parameters.
>   - implement parameters that are defined by OGC Testbed initiatives or non-OGC extensions to the OGC API standards.
>   - implement support for parameters that were defined in older versions of the standards but were since removed from those standards. 
>   - implement vendor-specific parameters.
>   - ignore unknown/unrecognized parameters.
>   - return a response with a status code of 400 and an exception report indicating unrecognized query parameters.
>   - return a response with a status code of 30x redirecting the client to a more correct version of the request.
> 
> In either case, while a service implementer should endeavour to provide as much detail in the server's API definition as the API definition language allows, there is no requirement for it to list every endpoint for which there is a non-404 behaviour, for it to list every possible query parameter that might affect the behaviour of the endpoint, or for it to list every possible value that each query parameter might accept.

Note that nary a requirement is present.

**Comment by cmheazel** [comment]
Rewrote section 8.1.3. It now includes two requirements and two permissions. 
The requirements call for a 400 response if the parameter name is not specified in the API definition and if the value of the parameter is invalid. 
The permissions allow for a parameter to be specified by a range of parameter names (such as templates or regex) and allows the server to correct malformed parameter names.
The free-form parameter technique for OpenAPI from API-Features (section 7.6) has been added to section 10.

**Comment by pomakis** [comment]
Part A of the first permission states:

> The specification of a query parameter in the API definition MAY encompass a range of parameter names. Any query parameter which falls within the specified range can be considered "specified" in the API definition.
>
> Examples of a parameter range include:
>
> An enumerated list of alternate capitalizations, spellings, and/or aliases of parameters,
>
> A reqular expression which defines the valid parameter names,
>
> A URL Template segment which defines the valid parameter names,
>
> [...]

If I have the following query-parameter declaration in my OpenAPI document:

          {
            "name": "geodata",
            "in": "query",
            "description": "A comma-separated list of collection identifiers indicating the collections to be rendered.  Each of the specified collections must be renderable in the specified style.  The leftmost collection in the list will be rendered bottommost, the next one over that, and so on.  In the absence of a geodata parameter, all of the collections that are renderable in specified style are rendered, in the order that the server deems most appropriate.",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "AgricultureSrf",
                  "CulturePnt",
                  "CultureSrf",
                  "Daraa_DTED",
                  "Daraa_mosaic_2019",
                  "FacilityPnt",
                  "HydrographyCrv",
                  "HydrographySrf",
                  "MilitarySrf",
                  "SettlementSrf",
                  "StructurePnt",
                  "TransportationGroundCrv",
                  "UtilityInfrastructureCrv",
                  "UtilityInfrastructurePnt",
                  "VegetationSrf"
                ]
              }
            },
            "style": "form",
            "explode": false
          },

and I wanted to advertise that I also accept the following:

    Geodata
    GEODATA
    collections
    Collections
    COLLECTIONS
    Collection_ids
    Collection_IDs
    COLLECTION_IDs
    collectionids
    collectionIds
    collectionIDs
    Collectionids
    CollectionIds
    CollectionIDs
    COLLECTIONIDS

a) How do I do this in OpenAPI?

And once I do,

b) How will the client be able to distinguish between the canonical form (i.e., the one actually prescribed by the specification) and its accepted alternatives?  Will a simple form-based client application provide the user with a pointless drop-down list of all the options?

c) Will my server really still be required to throw 400 error if it receives a parameter called "GeoData"?

d) What's the value if this extra complexity in the OpenAPI description?

**Comment by pomakis** [comment]
The /per/core/query-param-tolerance permission is exactly what I was looking for; thanks.

I have a question about part A of the /per/core/query-param-specified permission, though.  It states:

> The specification of a query parameter in the API definition MAY encompass a range of parameter names. Any query parameter which falls within the specified range can be considered "specified" in the API definition.
>
> Examples of a parameter range include:
>
> - An enumerated list of alternate capitalizations, spellings, and/or aliases of parameters,
>
> - A reqular expression which defines the valid parameter names,
>
> - A URL Template segment which defines the valid parameter names,
> 
> [...]

How does one specify parameter name ranges in OpenAPI?

**Comment by pomakis** [comment]
One other comment.  The /req/core/query-param-unknown requirement, which states:

> The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that is not specified in the API definition.

is incompatible with the new accompanying paragraph which states:

> there is no requirement for [the API definition] to [...] list every possible query parameter that might affect the behaviour of an endpoint

The former requires every accepted query parameter to be listed, where the latter provides some wiggle room for allowing the server to accept undocumented parameters.  FWIW, I think allowing undocumented parameters is a very useful ability in software systems in general.

**Comment by cmheazel** [comment]
@pomakis Regarding expressing parameter name ranges in OpenAPI - as far as I know it's not supported. But I see no reason to restrict implementations due to the current limitations of OpenAPI.  We can either lobby for changes to OpenAPI, define our own extension, or get creative in how we use it.  
Section 10 already documents how you can specify additional parameters in the OpenAPI document that are not validated against the schema. In the simplest case this is a statement that any parameter would be accepted. Other techniques could be developed as needed.

**Comment by cmheazel** [comment]
@pomakis The /req/core/query-param-unknown states that the parameter must be "specified". It does not define the term "specified".  /per/core/query-param-specified goes on to explicitly allow parameters to be "specified" in ways other than an enumeration of fixed values. 
So there is no incompatibility.  /req/core/query-param-unknown states that they must be specified, /per/core/query-param-specified defines what qualified as specification.

**Comment by pomakis** [comment]
I honestly don't see any point in explicitly enumerating the alternate capitalizations, spellings and/or aliases of parameter names.  That would actually be doing the clients a disservice, because not only would it give them a thicker, more complicated API definition document to wade through, but it wouldn't give them any indication as to which alternative is the canonical form (i.e., the one dictated by the specification).  And even if there was a way of determining that, why would the client ever want to know what the accepted alternate capitalizations, spellings and/or aliases are anyways?  Also, simple form-based clients would have to implement extra logic to avoid presenting the user with pointless drop-down lists of alternatives.

It all seems like a counter-productive over-specification, expecially since the
/per/core/query-param-tolerance permission now exists.

**Comment by cmheazel** [comment]
@pomakis What we really need is an API definition language which would allow you to define parameter names using a regular expression. Even better if it also supported a URL to a separate data dictionary. That would solve our DescribeFeatureType issue. Unfortunately we don't have such a language (yet).

**Comment by cmheazel** [comment]
@pomakis explicitly enumerating the alternate capitalizations, spellings and/or aliases is what we are tying to avoid.

**Comment by pomakis** [comment]
> @pomakis explicitly enumerating the alternate capitalizations, spellings and/or aliases is what we are tying to avoid.

Agreed.  So perhaps the bullet "an enumerated list of alternate capitalizations, spellings, and/or aliases of parameters" should be removed from /per/core/query-param-specified.

**Comment by cmheazel** [comment]
@pomakis Done!

**Comment by cmheazel** [comment]
February 1 - Permission 4 - remove bullet three. 
Close after modification has been made - NOTUC

**Comment by cmheazel** [comment]
Modification made - 2/1/21
