### ISSUE TITLE
Form/pattern of new link relations created by OGC ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-common#161]
The purpose of this issues is to stimulate discussion about new link relations that OGC might need to create.  Specifically, this issue is about the form/pattern of those link relations.  I have seen several forms/patterns floating around (e.g. rel=ogc:blah:blah) and I wanted to create an issue to focus the discussion.

My personal opinion is that new links relations should be URLs **_BUT_** only if OGC can **_guarantee_** that those URLs, if plopped into a browser, will resolve to some page that provides an explanation about what the relation is about.  If OGC cannot guarantee that, then we should use some shorter pattern like rel=ogc:blah.

Comments welcome!

**Comment by ghobona** [comment]
@pvretano The form of link relations is one of the topics addressed in the proposed policy on OGC API naming. There was a presentation to the TC today via teleconference.

Please refer to the email sent by @ogcscotts today with the title "OGC Naming Authority new part to Policies and Procedures for TC review". The email contains a link to the recording.

**Comment by cmheazel** [comment]
The specification need to be brought into conformance with the OGC policy then this issue can be closed.

**Comment by joanma747** [comment]
Action. Use the NA recommenced rel names and close the issue. In 2020-09-28 meeting

**Comment by cmheazel** [comment]
Core has been updated to comply with the proposed convention for OGC link relation types.

**Comment by cmheazel** [comment]
API-Common GeoData has been updated as well.
