### ISSUE TITLE
Bounding Box vs Subsetting

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#164]
Add explanatory text to API-Common Part 2 about the purpose and limitations of the bbox parameter.

1 - It is a simple, general filtering capability
2 - It addresses a common user practice of selecting an area of the screen as the area of interest
3 - It is not required to support precise coordinate selection
4 - It is not required to support sub-setting
5 - It assumes a 2, or at best 2.5 dimensional "map" view of the data

Related issue #43

**Comment by chris-little** [comment]
@cmheazel In API - EDR we use the bbox filtering functionality to be 2/3/4D. This is an easy and obvious extension, using ISO8601 notation for the temporal dimension, even if many existing tools cannot readily visualise the selection.
I suggest that your last line should read something like: 
`5 - It assumes at least a 2 dimensional "map" view of the data`

**Comment by cmheazel** [comment]
@chris-little Doesn't the dateTime parameter provide the same function? It supports both time instances and time periods.

**Comment by ghobona** [comment]
**2020-09-15 OGC API Cross Cutting Issues session during OGC Member Meeting**

The following resolution was agreed upon during the session:

- Given that OGC API – Features has demonstrated BBOX support for 3 dimensions, yes, bbox in OGC API – Common should support 3 dimensions if CRS allows it.
- Support for 4 dimensions could also be supported, using the approach used in OGC API – Features. The fourth dimension should be handled as a separated parameter. e.g. either using the existing datetime parameter or using the time axis of subset.

**Comment by ghobona** [comment]
Given the 2020-09-15 resolution, I propose that this issue is closed at the next OGC API - Common SWG meeting.

**Comment by cmheazel** [comment]
The bbox parameter in API-Common Part 2 supports both two and three dimension geometries.  API-Common Part 2 is also explicit about the extent being extensible.  The standard does not address how you would filter on an extended extent.  That is likely specific to the extension and cannot be captured in API-Common Part 2

**Comment by cmheazel** [comment]
In accordance with the resolution of issue #91, the extent structure has been reduced to zero or more spatial bounding boxes and temporal intervals. Work has also begun on a subsetting conformance class. The subsetting conformance class will address the more complex cases described in this issue.
