### ISSUE TITLE
Subset as a common building block for clipping in temporal, spatial (including height) and additional dimensions

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-common#167]
As highlighted by @joanma747 at the Coverages sprint (https://github.com/opengeospatial/ogc_api_coverages/issues/84#issuecomment-671903709):

BBOX axis order is confusing.
Subset has a very unambiguous syntax, and we can refine the syntax to be more elegant and lighter by not having to repeat the `subset` keyword for every dimension.

I propose again `subset` as the common mechanism which will return trimmed or sliced data across at least OGC API - Maps, Coverages & Features:

`&subset=dim1(minVal:maxVal),dim2(minVal:maxVal)`

The equivalent of `&bbox=lon1,lat1,lon2,lat2` would be `&subset=Lat(lat1:lat2),Long(lon1:lon2)`

simple and unambiguous.

For features, unlike BBOX which is already defined as returning whole interesecting features, it would _clip_ the data, allowing to retrieve vector tiles (though this would also require a generalization parameter as well for multi-resolution tiles).

Axis names would be standardized for the default CRS84 / CRS84h crses, as well as for the temporal dimension.

There may be some details to resolve, but I believe this is doable.

**Comment by cmheazel** [comment]
Subsetting is a Conformance Class under API-Coverages. It may have relevance outside of that standard. Once the API-Coverages draft is stable we should bring it into Common as a potential "module".

**Comment by cmheazel** [comment]
Subsetting has been added as a proposed module under the proposals/subsetting directory.  Efforts to generalize the coverage specific text are underway.
