### ISSUE TITLE
Querying the maximum value for `limit`

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-common#173]
Features has a default limit of 10, and specifying a limit larger than the maximum may result in a 400 error.
There is currently no other way to query the maximum limit other than parsing the OpenAPI definition.

Clients should not be forced to parse OpenAPI definition to make use of the API.

A standard mechanism to query the maximum value of `limit` is necessary, so that a client could use that value if it prefers not to use paging.

While paging makes sense for an HTML representation, why do programmatic clients have to bother with the added complexity of paging when HTTP already has chunked transfer encoding which serves that streaming purpose?

**Comment by cmheazel** [comment]
Suggestion - allow limit values that exceed the servers max, but only return the servers max limit number of features (etc.). - Parameter values which exceed the limit will be accepted, but the results would be truncated and paged.

**Comment by cmheazel** [comment]
Approve suggestion approved by the SWG on the October 26, 2020 telecon.

**Comment by cmheazel** [comment]
Added a permission allowing servers to impose limits on the size of responses
Added a recommendation that clients be prepared to handle paged responses even when not asked for.

**Comment by jerstlouis** [comment]
> and it does not support **requested paging limit** * then it should clip the response to fit within that maximum response size.

**Comment by joanma747** [comment]
We contributed to 368 what we believe is the right solution.

```
C) The server SHALL return the maximum possible number of items if the limit 
parameter values greater than the one the server supports, rather than responding with an error.
```

**Comment by jerstlouis** [comment]
One thing to check is whether the server indicating its OWN maximum limit in the OpenAPI definition could potentially conflict with requirement 3 of Common:

http://docs.opengeospatial.org/DRAFTS/19-072.html#query-parameter-requirements

i.e. whether if the client specifies a larger limit that IT is able to support larger than the server, will be interpreted as an invalid value.

**Comment by cmheazel** [comment]
Created separate sections for parameter names and parameter values.  Added /per/core/query-param-value-tolerance based on /per/core/query-param-tolerance. Updated /per/core/query-param-invalid to accommodate /per/core/query-param-value-tolerance.

**Comment by cmheazel** [comment]
May 24, 2021 SWG - In text above recommendation 7 - the word page should not be quoted.  It should be in normal text format.
Once this change has been made this issue can be closed.

**Comment by cmheazel** [comment]
Change merged June 1, 2021
