### ISSUE TITLE
Add an attribution directly in the description of the collection

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-common#174]
This issue is a continuation of this one
https://github.com/opengeospatial/OGC-API-Sprint-September-2020/issues/11

Example of the German open data requirement:

The user must ensure that the source note contains the following information:
* the name of the provider,
* the annotation "Data licence Germany – attribution – Version 2.0" or "dl-de/by-2-0" referring to the licence text available at www.govdata.de/dl-de/by-2-0, and
* a reference to the dataset (URI).
-----
In WMS Attribution: 
The optional <Attribution> element provides a way to identify the source of the geographic information used in a
Layer or collection of Layers. Attribution encloses several optional elements: <OnlineResource> states the data
provider’s URL; <Title> is a human-readable string naming the data provider; <LogoURL> is the URL of a logo
image. Client applications may choose to display one or more of these items. A <Format> element in LogoURL
indicates the MIME type of the logo image, and the attributes width and height state the size of the image in
pixels. 

----
Proposed alternatives are:

1.-
"attribution": "IGN (c)"    
"attribution": "[IGN (c)](http://www.ign.es)"     (Markdown)
"attribution": "<a href='www.ign.es'>IGN (&copy;)</a>"     (Markup)

2.-
"attribution": {
   "title": "IGN"
   "links": {
       //one for the organization and another for the logo (and another to the dataset)
   }
}

3.- 
"attribution": {
   "title": "IGN"
   "url": "www.ign.es"  //this can be a link
   "logo": "www.ign.es/logo"  //this can be a link
   "licence": {      // This can go into links 
      "title": "dl-de/by-2-0"
      "url": "www.govdata.de/dl-de/by-2-0" 
   }
}

----

We will ask for feedback to the other groups.

**Comment by cportele** [comment]
The attribution information is for display to users and there is no generally accepted model for attribution information. Therefore, option 1 with support for markup (HTML or Markdown) seems to be the most appropriate. 

Unsurprisingly, HTML seems to be used in cases where data is shown using a browser (e.g. Leaflet, OpenLayers, Mapbox Styles, Mapbox GL).

**Comment by joanma747** [comment]
We agreed on 2020-11-02 telco to use this solution (no much other feedback was obtained from emailing the API SWG's about this).

"Attribution" **should be short and intended for presentation** to make it "fit" in the right down part of a map (the use case we are trying to fix). Parts of the text can be links to other resources if more "explanation" is needed. 

So a solution like this works:
"attribution": "<a href='www.ign.es' rel=' '>IGN</a> <a href='www.govdata.de/dl-de/by-2-0'>(c)</a>"

A **Metadata link** can be used to provide **more details** about attribution.

**Comment by joanma747** [comment]
It will be on the core defined as a "attribution" OGC API schema fragment as well as the link relation type. It will not have requirements BUT it will not be added in the landing page core schema (we agreed it could be confusing for a "complex" service) but everybody can add it if needed.

**Comment by cportele** [comment]
OpenAPI schema:

```yml
ResourceWithAttribution:
  type: object
  properties:
    attribution:
      type: string
      title: attribution for a resource
      description: The "attribution" should be short and intended for presentation to a user, for example, in a corner of a map. Parts of the text can be links to other resources if additional information is needed. The string can include HTML markup.
```

This is a building block that can be reused in any resource by using `allOf`. This, for example, adds the attribution property to a Collection resource:

```yml
CollectionWithAttribution:
  allOf:
  - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml'
  - $ref: '#/components/schemas/ResourceWithAttribution'

```

**Comment by cmheazel** [comment]
I have added the attribution property described by @cportele to the JSON Schema for the landing page.  This way it provides an example of how to add attribution properties without mandating a solution. 

Is this sufficient?
Should we include a short discussion of the landing page properties in the standard?

**Comment by m-mohr** [comment]
I don't see a commit reference in this issue. Where can we find it for review? (Still confused which branch is the one to look at...)

**Comment by joanma747** [comment]
In 2020-11-30 telco, we agree that it will be the attribution of the API (service) and not to the data or processes.

Check that the description for the landing page in the document will describe the title, description and  attribution (eventually with an example), but no requirements will be added.

**Comment by jerstlouis** [comment]
@joanma747 The resolution as written is still a bit confusing...

When a concept of dataset is introduced, and the landing page/services maps to the dataset, then you could say that it is in fact the the attribution is in fact for the data.

When a specific collection is attributed, then the attribution is for that specific colleciton.

@m-mohr The idea was that either or both could have attribution: at the landing page for the whole dataset, and at the collection level for a particular collection.

**Comment by cmheazel** [comment]
@jerstlouis The scope of an attribution is the current context. In the case of API-Common, the context is the landing page. If we add a `collections` path, then the collections resource can inherit the attribution from the landing page, or declare its own attribution. Likewise, a `collection` can inherit attribution from `collections` or declare their own. However, the reverse is not true. Declaration of the attribution of a `collection` says nothing about the attribution of the landing page.

**Comment by jerstlouis** [comment]
@cmheazel I agree 100% with that, I just find that the `not to the data` mention in the resolution captured today could be interpreted as excluding the use case of the attribution in the landing page to attribute the dataset.

**Comment by cmheazel** [comment]
Added a short writeup on the landing page metadata elements (attribution in particular) to section 8.2.1. Note that an example of the use of markup in the attribution element has already been added. Plus both the JSON and YAML schemas have been updated.

**Comment by jerstlouis** [comment]
While attribution of the dataset in the landing page has been taken care of for Part 1, let's make sure to leave this issue open to address the Part 2 aspect of it for attributing a specific collection.

**Comment by cmheazel** [comment]
Part 2 has been addressed.

**Comment by cmheazel** [comment]
5/10/21 SWG - OK to close.
