### ISSUE TITLE
What happens with LanguageString and other things in defined in OWS Common 06-121r9?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-common#175]
I have detected the following issue:

Some old OWS services used data models (e.g. WMTS and WPS) that relay on elements defined in OWS Common: e.g. ows:LanguageString, ows:BoundingBox, ows:Keyword... These are small things. None of them are specific of "services" and they are just small concepts defined UML and XML that are worth sharing. The issue emerges when the same data models are used in the new APIs. Both OGC API Tiles (actually 2D-TMS) and OGC API Processes become dependent to OGC API Common and OWS Common at the same time. Is that good?

In the revision of 2D-TMS, I'm just duplicating the elements from OWS Common to avoid the dependency, but do we need a OGC CommonClasses standard instead? (something like in SWE Common but more general?)

I presented this issue to the OAB but they want us to discuss it here first.
I have catalogued the issue as "core" it is kind of "core" but I understand It is an independent conformance class that can go to another document but the document should not be delayed.

More details on what is needed here: https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/standard/clause_5_conventions.adoc

Joan Masó
CREAF

BTW, I have learnt from Clemens that ows:LanguageString becomes only "String" in the OGC API world as the HTTP language negotiation works in a way the response is supposed to be only in one language. But this does not invalidate ows:LanguageString in data models that can be used in other environments too.

**Comment by cmheazel** [comment]
@joanma747 The Service Identification and Service Provider metadata has been captured in a JSON schema which is an extended form of the OpenAPI Info object. A recommendation has been added to API-Common Part 1 that a link to this resource (service-meta) should be included in the landing page. That allows the metadata to exist as either part of an OpenAPI document or as a separate resource. Note that core only recommends that the metadata be provided.  The JSON schema itself is defined for the OAS conformance class. Additional API definition languages will have to use their own approach to supporting this recommendation.

Bounding Box and other re-usable parameters are defined in Part 2.

**Comment by cmheazel** [comment]
API-Features does have a "String internationalization" section (7.10). Should we include this content in Common?

**Comment by joanma747** [comment]
Related with this, I notice that we have a folder called "openapi" that contains a folder called "schemas" with JSON schemas that are used in OpenAPI but ARE NOT OpenAPI exclusive at all. In fact, they are schemas for validating JSON encodings of "things"  such as links, landing pages etc... In other words, they are useful beyond Open API and the OpenAPI conformance class. E.g TMS is going to use "links.json" but TMS has nothing to do with OpenAPI

To we need another structure of "files" to avoid confusion on this?.

**Comment by joanma747** [comment]
We decided to replicate section 7.10 (http://docs.opengeospatial.org/DRAFTS/17-069r4.html#string_i18n) in common part 1 in a motion 2021-02-08 telco.

**Comment by cmheazel** [comment]
February 8 update to Working branch:
Added section 7.10 from Features as section 8.1.6 in Common. 
Added content after Recommendation 7 (section 7.9) from Features to the re-numbered section 8.1.7 in Common. the new section 8.1.6 references this content.
