### ISSUE TITLE
Consider revising the structure of Exception responses

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-common#180]
There was a suggestion to consider revising the structure of Exception responses, so that they could be as informative as those from OWS Common.

Currently the structure is as shown at https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/exception.yaml

One suggestion is to have an array of descriptions.

The 'code' property is not well defined and it appears to duplicate the role of the HTTP status code.

**Suggestion that there would be a recommendation to use the JSON Schema for exception responses, and the Guide would provide more information.**

**Comment by cmheazel** [comment]
This issue was resolved in issue #73

**Comment by joanma747** [comment]
The resolution in #73 applies: "API-Common Part 1 - the exception schema has been updated to conform with RFC 7807. This schema will be updated to conform with the revised version of RFC 7807 once it is finalized." Will be also applied to part 2 collections

**Comment by cmheazel** [comment]
API-Common Part 2 is now in-line with Part 1.
