### ISSUE TITLE
Add "processes" to "collections" and "items"

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-common#19]
There is a need to have the concept of simple processing that has a collection of items (or an item) as input and result in other resources. For instance, the creation of a map by applying a style or the change in a CRS by applying a CRS transformation. Should the core say something about it?

**Comment by cmheazel** [comment]
Not at this time.  This is the sort of capability that I think should first be explored by one or more of the other API specs.  If we see a common capability emerging, then we can consider it for common.

**Comment by joanma747** [comment]
This capacity is already emerging in WMS where a collection is transformed into a map my applying a style; or map tile is produced in a CRS different than CRS84 by applying a tilematrixset. I agree that we have not tested it yet.

**Comment by jyutzler** [comment]
There is already an OGC API Processes SWG. I recommend that this be closed.

**Comment by cmheazel** [comment]
This concept can be explored in the Architecture section of the Users Guide. In particular, under the Processes sub-category.

**Comment by jerstlouis** [comment]
I believe that this is well addressed by [OGC API - Processes - Part 3: Workflows and Chaining](https://docs.ogc.org/DRAFTS/21-009.html), specifically the "Collection Input" and "Collection Output" requirement classes.

This was also the vision outlined in #17 , and similar language is already included in section 5.2 Processes of the [Common User Guide](https://docs.ogc.org/guides/20-071.html#toc12):

> Processes take one or more datasets as input, add parameters, and produce one or more datasets as output. 
> All of these kinds of processes could share aspects such as taking in an OGC API dataset as input and their output being usable as an OGC API dataset, for direct access and/or asynchronous delivery, and support multiple data partitioning/access mechanisms, estimates/billing elements, and so on.

@joanma747  Can we close this issue?
