### ISSUE TITLE
Content of "6.3 Link relations"

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-common#192]
The text states:

> The link relationships used in API-Common Core are described in Table 2.

Currently table 2 includes a not so small list of link relation types that are not used in Common Core. Either change the description of table 2 or reduce the content in table 2.

In addition, the section includes a permission and a recommendation that belongs to the Core requirements class, but that requirements class is defined in clause 7. The normative text should either be moved there, or the text should be changed to informative text.

**Comment by joanma747** [comment]
In 2021-02-08 telco we agreed on reducing table 2 to contain only the rels used in part 1.

**Comment by cmheazel** [comment]
February 8 update to Working branch 
Done!
