### ISSUE TITLE
i18n in ogcapi-common

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/ogcapi-common#198]
ogcapi-features has a topic about i18n, this aspect seem not available in common yet, but are we adopting similar in common, for use in other standards, such as records/tiles?

http://docs.opengeospatial.org/DRAFTS/17-069r4.html#string_i18n

A typical usecase is that the server has an english and french title/abstract for the collection or item, and returns either one according the the accept-language.

**Comment by cmheazel** [comment]
Section 8.1.6 of API-Common Part 1 is identical to the API Features section 7.10.
