### ISSUE TITLE
OpenAPI with external references

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#202]
The current example OpenAPI document for API-Common Part 1 includes external references to the response schema. This does not work in SwaggerHub, but does appear to be legal.  Re-test this approach using KaiZen.  If it also fails under KaiZen, then re-structure the example OpenAPI document to include the schema.

**Comment by joanma747** [comment]
Or wait to see support to OpenAPI 3.1 in the SwaggerHUB. I believe we still have time after the OAB revision and RFC.

**Comment by cmheazel** [comment]
The updated example OAS document in API Part 1 demonstrates referencing external OAS components, and validates in Swaggerhub.
