### ISSUE TITLE
Avoid conf in ATS identifiers

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-common#204]
It would be better if the ATS identifiers didn't use "conf" (which suggests conformance class). 

It can still use the name of the conformance class though. So it might be `/ats/core/api-definition-op` instead of `/conf/core/api-definition-op`

**Comment by cmheazel** [comment]
This is an issue that must be addressed by the OGC Naming Authority. We simply follow their direction.

**Comment by bradh** [comment]
Valid.

Have raised ticket for Naming Authority. Any work is pending policy changes, which shouldn't block this.
