### ISSUE TITLE
Path to resources in the OGC schema repository

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-common#21]
While editing the Features spec, I need to include references to the future location of the OpenAPI building blocks etc. Can we agree on the general approach?

My proposal would be 

`http://schemas.opengis.net/ogcapi/{resourceType}/part{partNumber}/{majorVersion}.{minorVersion}` 

as the base URL. The OpenAPI definitions could sit in a sub directory "openapi". I.e., for OGC API - Features - Part 1: Core we would get

`http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/`

Any concerns about this approach?

Considerations:

* Collect all OGC API building blocks under "ogcapi" at the top level.
* I would have just used "1", "2", etc. for the parts, but added the "part" prefix to be consistent with existing examples (see http://schemas.opengis.net/infragml/).  
* I would not place OpenAPI files at the base URL level as standards may have other resources, too. For example, XSDs.

cc: @gbuehler

**Comment by cmheazel** [comment]
I like it.

**Comment by cmheazel** [comment]
Updated API-Common Core to comply.

**Comment by joanma747** [comment]
We now this places with OpenAPI documents and schemas:
http://schemas.opengis.net/ogcapi/features/part1/1.0/
https://github.com/opengeospatial/oapi_common/tree/master/core/openapi
https://app.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0

How can we syncronize all this?

We see that OGC API features decided to have the schemas in the schemas.opengis.net but the examples on github for now. Are we going to do the same?

**Comment by cportele** [comment]
Sorry for not being able to attend the meeting today...

A comment on the approach in Features:

* The reference schemas are on schemas.opengis.net as this is OGC policy. Other locations like SwaggerHub domains are for convenience and GitHub both for convenience and to support the development/maintenance of the building blocks.
* While we manage the examples on GitHub and SwaggerHub, the official link goes to http://schemas.opengis.net/ogcapi/features/part1/1.0/examples, which redirects to GitHub for now, but this can be changed in the future, if needed.

**Comment by cmheazel** [comment]
API-Common Parts 1, 2, and the Users Guide have been updated to point to schemas.opengis.net.

**Comment by cmheazel** [comment]
This issue will be closed once we have confirmation that the API Common resources are available on schemas.opengis.net.

**Comment by cmheazel** [comment]
Redirect the URLs back to the  GitHub. Schemas only move to schemas.net after approval.

**Comment by cmheazel** [comment]
Corrected in core - 
Since the schemas will not be posted until they are approved, the links point to the GitHub site for now.

**Comment by ghobona** [comment]
The schemas will be deployed to schemas.opengis.net after the standard has been approved.
