### ISSUE TITLE
Landing page media type in Example 2 of Core is wrong

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-common#210]
As specified in Requirement 23 of OGC API-Common- Part 1, the media type of the OpenAPI definition document is supposed to be `application/vnd.oai.openapi+json;version=3.0`. This is also stated in OGC API - Features.

However, Example 2 in the current draft of OGC API - Common - Part 1 states the media type as `application/json`. See attached.

Please modify Example 2 to list the media type as `application/vnd.oai.openapi+json;version=3.0`.

![commonlandingpage](https://user-images.githubusercontent.com/18121038/109302170-d9a27c80-7830-11eb-8cfa-c7865066f0e5.png)

**Comment by cmheazel** [comment]
Example is updated.  Question, should the -f parameter use the open API MIME type as well?
