### ISSUE TITLE
Possible invalid link rel value in example

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-common#218]
http://defs.opengis.net/vocprez/object?uri=https%3A//www.opengis.net/def/rel/ is the "register of link relation types used by OGC standards".

https://github.com/opengeospatial/ogcapi-common/blob/8a8d38e8e2add7955e1b1ff1996aeeca4ac8a497/core/openapi/examples/LandingPageExample.json#L19 specifies a link `rel` of `http://www.opengis.net/def/rel/ogc/1.0/data-meta` which is not a registered relation type.

That might require update of the OGC NA register, or change in the example. Not sure - please close if this is a false alarm.

**Comment by ghobona** [comment]
@bradh Thanks for raising the issue.

The register is actually at http://www.opengis.net/def/rel

However, we are currently upgrading the Definitions Server so there are some links that appear to be broken. We will fix them over the next couple of weeks.

**Comment by bradh** [comment]
`http://www.opengis.net/def/rel/ogc/1.0/data-meta` is now in the register, so I guess that this is solved.
