### ISSUE TITLE
Items as an extension point

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#221]
The /items resource and itemType element have been defined in Common Part 2 with the intention of providing a common integration point for geospatial collections defined by OGC Web API standards.  The challenge is to define this integration point in enough detail to be useful without imposing unnecessary constraints on the integrated standards.  

Related issues: #107

**Comment by joanma747** [comment]
please remove:
Recommendation 3 | /rec/collections/rc-md-items-descriptions
that seems related to "feature schemas".

**Comment by cmheazel** [comment]
A: Retained.  The text reads "external schemas or descriptions exist that provide additional information about the structure or semantics of the collection".  This can be any resource which provides additional information about the collection.  The effect is to authorize the use of the `describedBy` association.

B: Change has been made.

C: Section 8.1.3 has been removed

D: Table 2 has been updated.

**Comment by cmheazel** [comment]
May 24, 2021 SWG: OK to close.
