### ISSUE TITLE
Agree name for datetime

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-common#223]
`datetime` is a very commonly used parameter outside of OGC. Should it be one word, or for consistency with the `use lower-kebab-case policy` be changed to `date-time`. 
or any of the other options such as lowerCamelCase, UpperCamelCase?

**Comment by jerstlouis** [comment]
We have already have the kebab-case policy, so I suggest we narrow it down to either keeping `datetime`, as defined by the published _Features_ standard, or change it to `date-time` to follow the policy considering it two separate words.

Spacetime is one word, maybe this is where datetime being a single word comes from ;)

**Comment by chris-little** [comment]
@jerstlouis I suspect spacetime, like datetime, comes from people not knowing where hyphen is on the  keyboard, and legacy software systems not supporting non-alphabetic characters in the names of things.

"spatio-temporal" is in the dictionary, but "spatiotemporal" is what gets the hits in G**gl* or Wikipedia.

We should resolve this quickly before EDR API and its several implementations advances into the wide world

**Comment by cmheazel** [comment]
Related to issue #224

**Comment by cmheazel** [comment]
May 3 SWG - Resolution is to keep datetime as a single word.  If datetime is a single word then the case issue (224) does not apply.
