### ISSUE TITLE
Revert name to Collections not Geodata

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-common#227]
1. I would like the OGC APIs treat time and the 3rd dimension are first class coordinates, not as 'after thoughts' ("we can always extend it later" - usually not true) The use of 'geodata' detracts from the temporal  aspects, and also implicitly sidelines, for example, building or engineering data.
2. 'Collection' is admirably neutral and describes precisely what Part 2 is about. The introductory paragraphs of the Scope use the word 9 (nine) times.
3.  Collection is defined, and not just in OGC.
4. Geodata does not have a definition.
Please revert to the original title for consistency with Features and EDR and W3C.

**Comment by cmheazel** [comment]
Document is GeoData
Resources are collections, collection, or collection description

**Comment by chris-little** [comment]
@cmheazel So, if it is all about collection resources, why is the document called GeoData? Is this branding before function? Will there be another part about collection resources that are not geodata, however defined?

**Comment by jerstlouis** [comment]
@chris-little 
As per the resolution of #140 , in Common - Part 2 (and ideally throughout the OGC API family of specifications conforming to it), we have agreed that _collection_ takes on a more specific meaning than the general computer science meaning of collection (i.e. a bunch of things, as implemented by lists and arrays). That is, a _Common - Part 2_ collection is specifically a collection of _data_, typically geospatial (which will also often have a temporal aspect).

It was agreed to rename the document _Geospatial Data_ to make it more obvious that this specification is not about a collection of anything, but it is the common OGC API specifications dealing with resources representing data.

However inside that specification, collection can be used as it is defined with the specific intended meaning, and it is the name of the data resource. It can also be used for query parameters (e.g. to list collections to render in _Maps_ and _Tiles_).

In _Processes_, all instances where _collection_ was previously used with its general computer science meaning have been replaced with _list_ to avoid confusion. e.g. lists of _processes_ or _styles_ are not collections (of spatio-temporal data) in the _Common - Part 2_ sense.

**Comment by cmheazel** [comment]
May 3, 2021 SWG: The resources described are Geospatial Data.  The path includes collections and instances of Geospatial Data.  Editor will make sure that the draft aligns with this distinction.  This issue will be closed once the draft has been checked for conformance with this resolution.

**Comment by cmheazel** [comment]
As written, the draft standard addresses spatial or geospatial resources which are grouped into collections. The distinction between the collections and the geospatial data resources which make up the collections seems clear.
