### ISSUE TITLE
Invalid values for parameters must lead to a 400?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-common#234]
Commons Part 1, §8.1.3, requirement 3 says:

> The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that has an invalid value.

What is an invalid value?

Some examples:
- You have a limit parameter defined, type number with maximum value 100 in the OpenAPI Schema: Is passing a limit of 200 valid? Related issue: #173 
- You have a parameter to search for IDs. You pass ids=[1,2,3] but the server only has data with the IDs 2,3,4. Is that valid?

**Comment by cmheazel** [comment]
@m-mohr Please see "/per/core/query-param-value-tolerance".  This permission was added on May 18 in respose to issue #173 but I think it addresses your issue as well.

**Comment by m-mohr** [comment]
I can't find any mention of `query-param-value-tolerance` in this repository. Can you clarify where I can find this?

**Comment by cmheazel** [comment]
@m-mohr You will find PER_query-param-value-tolerance.adoc under ogcapi-common/general/recommendations/general/.

**Comment by cmheazel** [comment]
May 24, 2021 SWG - Agree that this issue can be closed.
