### ISSUE TITLE
Core: reference to OpenAPI 3.0.x

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#237]
A few editorial remarks on the reference to the OpenAPI spec: what happens when a version 3.0.4 would be released? I would suggest updating the reference to use the same wording as in the OGC API – Features spec. See also https://github.com/opengeospatial/ogcapi-features/issues/339#issuecomment-594409672

Note: In 10.1, it is stated that a dependency of requirements class http://www.opengis.net/spec/ogcapi-common-1/1.0/req/oas30 is 
OpenAPI Specification 3.0.**2**, that should be changed to OpenAPI Specification 3.0 (as the URI and the media type also indicate).

And perhaps example 4, JSON API Definition, should also be updated, in order to reflect that the latest patch version at the time of publication of the standard was 3.0.3 and not 3.0.2.

**Comment by cmheazel** [comment]
Recommended changes have been made.
