### ISSUE TITLE
Core: definition landing page

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#239]
W3C actually has a definition for "landing page", see https://www.w3.org/TR/urls-in-data/#dfn-landing-page. So a suggestion for update:

**landing page**
page whose primary purpose is to contain a description of something else ([W3C, URLs in Data Primer](https://www.w3.org/TR/urls-in-data))

Note 1 to entry: Landing pages often provide summaries or additional information about the thing that they describe. Examples are landing pages for images on Flickr or videos on YouTube, which are HTML pages that embed the media that they describe and provide access to comments and other metadata about it. Landing pages for documents are often tables of contents or abstracts.

Note 2 to entry: A landing page for a Web API serves as the root node of the API Resource tree and provides the information needed to navigate all the resources exposed through the API.

Depending on how much extra notes you want in the standard, you could either both of the previous notes or only the second one (the first note is copy-pasted from https://www.w3.org/TR/urls-in-data/#dfn-landing-page).

**Comment by heidivanparys** [comment]
Note: related to https://github.com/opengeospatial/ogcapi-features/issues/465.

**Comment by cmheazel** [comment]
Recommended changes have been applied.  Thanks!  I have been looking for an authoritative definition of landing page.
