### ISSUE TITLE
Core: definition of resource

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#240]
Editorial: I would suggest using the following instead:

resource
entity that might be identified ([Dublin Core Metadata Initiative - DCMI Metadata Terms](
https://www.iso.org/obp/ui/#iso:std:iso:15836:-2:ed-1:v1:en:term:3.1.10))

web resource
resource that is identified by an HTTP URI

I am not sure the definition of resource can be found on https://www.dublincore.org/specifications/dublin-core/dcmi-terms/ but the ISO version defines "resource" like that, see link above.

Perhaps some notes can be added referring to the dissertation in the current definition, if needed. Or some of the text in https://www.rfc-editor.org/rfc/rfc3986.html on "resource".

In addition: add perhaps the following reference (or similar) to the bibliography:
[DCMI] DCMI USAGE BOARD. DCMI Metadata Terms [online]. DCMI Recommendation. Dublin Core Metadata Initiative, 20 January 2020. Available from: http://dublincore.org/documents/dcmi-terms/. This standard is also published as ISO 15836:2019, 
Information and documentation — The Dublin Core metadata element set.

Perhaps a line should be added stating that in the remainder of the document resource will be used for brevity, but web resource is of course meant.

Related to https://github.com/opengeospatial/ogcapi-features/issues/558.

**Comment by cmheazel** [comment]
July 12 - use definition from RFC 3986.

**Comment by cportele** [comment]
Question: Could you clarify, what "use definition from RFC 3986" means and what the proposed definition is? I do not find a definition of "resource" in RFC 3986. Except maybe "whatever might be identified by a URI", but the proposal from @heidivanparys is clearer.

Related: Did you take the [discussion/decision of the Features API SWG](https://github.com/opengeospatial/ogcapi-features/issues/558#issuecomment-874163429) on basically the same comment on a different OGC document into account in the discussion?

**Comment by cmheazel** [comment]
@cportele Yes, but it's not clear exactly what the SWG agreed to. 

I agree that definitions should be consistent across the OGC API Standards.  The trick is to make that happen. The OGC Definition Server should do that for us.  So I suggest we kick this issue over to the OGC NA.

Currently the term "resource" is on the definition server but the entry does not include a definition. Let's propose Heidi's definition for Resource and see if we can make it official. 

Web Resource is another matter. 

The term "Web Resource" does not appear anywhere in API Common (or Features part 3 for that matter), we have no rationale to include it as a separate item in the terms and definitions. But building off of Heidi's recommendations, perhaps we can do the following: 

**resource / web resource:**
1. entity that might be identified (Dublin Core Metadata Initiative - DCMI Metadata Terms)
2. (Web Resource) resource that is identified by an Internationalized Resource Identifier (IRI).
NOTE:: In this document the term "resource" will refer to both generic Resources and Web Resources.

This would require that we establish an OGC authoritative definition for Web Resource.

**Comment by cportele** [comment]
@cmheazel - Sounds good to me, with one amendment: The standardization target of the OGC API standards is typically Web APIs, so when we say "resource" we always mean "web resource" using the definitions proposed by Heidi - at least this is the case for the standards of which I am an editor. I would therefore keep the two terms separate and add a note in the OGC API standards under the "resource" definition about this.

**Comment by cmheazel** [comment]
Changed both Part 1 and Part 2 to:

[[resource-definition]]
* *Resource* +
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>) +
+
[width="90%",cols="1,10"]
|===
|*NOTE:*| The term "resource", when used in the context of an OGC Web API standard, should be understood to mean a <<web-resource-definition,Web Resource>> unless otherwise indicated. 
|===

and added 

[[web-resource-definition]]
* *Web Resource* +
a <<resource-definition>> resource that is identified by an IRI.

We should update the definition server accordingly.

**Comment by cportele** [comment]
I have made the change in a [PR to Features](https://github.com/opengeospatial/ogcapi-features/pull/608), too. Both in Part 3 and also in Part 1.

There is a small difference between the current update in Common. Instead of "identified by an IRI" I have used "identified by a HTTP URI" since IRIs/URIs in other schemes identify non-web resources (e.g. UUIDs or e-mailboxes).

**Comment by cmheazel** [comment]
July 19 meeting - definitions are acceptable but use URI instead of IRI.  Align with the update to Features.
