### ISSUE TITLE
Core: resource type in terms and definitions

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#241]
Minor editorial comment:

1. The second part of the definition of "resource type" should be moved to a note instead.
2. "The definition of something is not the same thing as the something": "the definition" should be removed from the definition (🙂). That leaves "type of resource". Perhaps it is enough to just use a synonym? E.g. "kind of resource"? I don't think the reader will be in doubt of what is meant in this case. See also https://www.oxfordlearnersdictionaries.com/definition/english/type_1 and https://www.freethesaurus.com/type

So:

**resource type**
kind of resource

Note to entry: Resource types are re-usable components which are independent of where the resource resides in the API.

**Comment by cmheazel** [comment]
Recommended change has been applied.
