### ISSUE TITLE
Core: addition info on RPC style in section 7.1

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#242]
Editorial:

Current the text states:

> OGC Web Service (OWS) standards implement a Remote-Procedure-Call-over-HTTP architectural style using XML for payloads. This was the state-of-the-art when OGC Web Services (OWS) were originally designed in the late 1990s. [...]

For people that are trying to get familiar with the old suite of standards and/or the new suite of standards and try to understand the difference between the architectural styles, it is a bit of a jungle sometimes. I think it would be helpful to add more background information in the form of a link to another document diving deeper into that topic.

I tried to find something useful, perhaps the following could do, but they may very well be more suited articles out there.

Feng, Xinyang, Shen, Jianjing and Fan, Ying: REST: An alternative to RPC for Web services architecture. In: 2009 First International Conference on Future Information Networks (2009), https://doi.org/10.1109/ICFIN.2009.5339611 (also available on http://www.ece.uvic.ca/~zhengl/seng422/materials/Lab7_paper.pdf)

**Comment by cmheazel** [comment]
June 12 - add link to ogcapi.ogc.org to learn more about OGC APIs.
Approved to close once this mod has been made.
