### ISSUE TITLE
Core: URIs of normative statements in 8.1.3 Query parameters

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-common#244]
1. The text of the requirement 3, A, is missing a hyphen between value and tolerance: it should be "/per/core/query-param-value-tolerance does not apply" instead of "/per/core/query-param-value tolerance does not apply".
2. Consider using /query-param-name-unknown, /per/core/query-param-name-specified and /per/core/query-param-name-tolerance instead of /query-param-unknown, /per/core/query-param-specified and /per/core/query-param-tolerance, as the section is called "Parameter Names".
3. Consider using /req/core/query-param-value-invalid instead of /req/core/query-param-invalid (in style with /per/core/query-param-value-tolerance) as the section is called "Parameter values".

**Comment by cmheazel** [comment]
Recommended changes have been made.
