### ISSUE TITLE
Conformance declaration as a string array

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-common#269]
OGC API - Common, Features and EDR specify the conformance declaration as a string array.

https://github.com/opengeospatial/ogcapi-features/blob/master/core/openapi/schemas/confClasses.yaml

https://github.com/opengeospatial/ogcapi-common/blob/master/core/openapi/schemas/confClasses.yaml

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/confClasses.yaml

The draft OGC API - Maps and Tiles specs constrain the declaration to say that it is a string array of URI format.

https://github.com/opengeospatial/ogcapi-maps/blob/master/openapi/swaggerHubUnresolved/ogc-api-common.yaml#L329

https://github.com/opengeospatial/ogcapi-tiles/blob/master/openapi/swaggerHubUnresolved/ogc-api-common.yaml#L329

NOTE: This is the Common yaml that is imported by the OGC API - Maps & Tiles openapi definition documents.

Specifying that the array is of URIs creates a problem for some code generators because they interpret that to be a different class.

For example, using OpenAPITools through Spring generated the following signature for OGC API - Maps:

`ConfClasses.addConformsToItem(URI conformsToItem)`

However it generated the following signature for OGC API - Features and EDR.

`ConfClasses.addConformsToItem(String conformsToItem)`

This is not a major issue because developers can modify the class to support different signatures and the messages will look the same in transit.

However, making the string array URI-formatted appears to create an additional hurdle for developers (at least for those that use Spring & OpenAPITools).

**Comment by joanma747** [comment]
The OGC API Tiles SWG realizes that is not his job to define the conformance schema. WE decided to trasfer it to common in a SWG meeting

**Comment by cmheazel** [comment]
July 19 - Since the OGC policies governing conformance classes make it impossible to have a valid value in the conformance resource that is not a URI, there is no harm in omitting the format=uri statement. This would also maintain consistency with API-Features. Resolution - no change.
