### ISSUE TITLE
bbox and datetime parameters

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#32]
bbox should include up to three dimensions and an optional crs.  How does this differ from OWS common?  Add text to justify the change.

**Comment by hylkevds** [comment]
It should also be specified how to deal with those parameters on collections that do not have a geospatial extend, or that do not have a time extend. Those parameters should not be mandatory for those collections.

I think the concept of specifying filters using separate parameters for each property is ultimately too limiting. It's not possible to specify how multiple filter parameters are to be combined (and/or/not, precedence) or to filter one property for multiple extends.
It would be better to drop these parameters from the first version, and add a proper (generic) filtering language in a future version.

**Comment by morpl** [comment]
I'm not sure if this should be in issue #43, here or in new issues, but I have a couple of comments on the bbox parameter:

In document 19-072 https://portal.ogc.org/files/91975, section 9.4.1, requirement 18, the bbox parameter isn't mandatory. In the current WMS, the bbox parameter is mandatory, so I would expect that some future OGC API standards could have a mandatory bbox parameter (also see #43). If I understand it correctly, they would not be able to comply with the Requirement Class "Collections". Has more fine-grained requirement classes to distinguish between strictly spatial collections and mixed collections been considered?

Regarding document 19-072 https://portal.ogc.org/files/91975, section 9.4.1, requirement 19: If a collection contains resources that have a spatial geometry and resources that are not associated with a spatial geometry, then A and C seem contradictory (I understand A to leave out resources without a spatial geometry and C to always include them). However, the alternative formulations that I can think of are much harder to read, and I think the meaning of the current formulation is clear. But how can I make a query that only includes resources with a spatial geometry in the result set? I would need some other parameter in addition to bbox to do so. 

Btw, the two last rows of the table in requirement 19 should be E and F (typo in standard/requirements/collections/REQ_rc-bbox-response.adoc).

**Comment by cmheazel** [comment]
API-Common Collections defines how bbox and datetime are applied against the extend element of the collectionInfo resource.  Use of those parameters for other resource types should be specified in the appropriate standards.
Recommend to be closed.

**Comment by jerstlouis** [comment]
I suggest that Common should define query parameters to be re-usable by OGC API specifications, which would then define how the response is affected by those parameters.

See e.g. https://github.com/opengeospatial/ogc_api_coverages/blob/master/standard/requirements/coverage-bbox/REQ_cov-bbox-definition.adoc (_Requests which include the Bounding Box parameter SHALL comply with API-Common requirement /req/core/rc-bbox-definition._)

Subset might be a better, or alternate, candidate to bbox/dateTime as discussed in https://github.com/opengeospatial/oapi_common/issues/62.

**Comment by cmheazel** [comment]
Close in deference to #167?

**Comment by ghobona** [comment]
**2020-09-15 OGC API Cross Cutting Issues session during OGC Member Meeting**

See the related resolution at https://github.com/opengeospatial/oapi_common/issues/164#issuecomment-693477644

**Comment by cmheazel** [comment]
This issue has been supersede by issue #164 which has been closed.
