### ISSUE TITLE
Part 2: Remove remaining mentions of /rm/collection

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-common#344]
Given that the requirements module `/rm/collection` has been removed, all other mentions of it should be removed from the document.

**Comment by jerstlouis** [comment]
Thanks @ghobona for pointing this out.

We've been focusing on the new req. classes lately, but perhaps next week when @joanma747 is back we can focus on reviewing the main Collections req. class.
I would think the referenced content is still there nearby in the same section 8, perhaps in another requirement. We need to clean this up.
