### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#43]
From the API Hackathon report:
(Map Tiles) The participants observed [https://github.com/opengeospatial/OGC-API-Map-Tiles/issues/14] that the extents and bounding box classes used by the OGC API - Map Tiles specification have been defined in different ways. The extent class defines a bounding extent as an array of numbers indicating bounding coordinates, whereas the boundingBox class defines the bounding coordinates as separate attributes for the lower and upper corner coordinates.

(Coverage) The participants expressed the need to inherit the BBOX and time parameters from OGC API - Common, however they also observed that there would be a need to identify a CRS for height. One of the suggestions was for each axis to have a separate coverage filter. The participants concluded that there is currently no construct in the Core part of the OGC API - Common specification that supports filtering of coverages.

(Common) The participants observed that there is a need for a CRS that is based on CRS:84 but that includes ellipsoidal height. EPSG:4979 and EPSG:4327 were suggested as a possible basis for such a CRS, but these use latitude/longitude as the axis order. It was agreed to discuss the issue of a height or elevation CRS with the WFS/FES SWG and the CRS Domain Working Group (DWG) at the OGC TC
meeting in Leuven. The WFS/FES SWG passed a motion at the OGC TC meeting in Leuven, the week
after the hackathon, proposing a new CRS named CRS84h that would be based on CRS:84 and
include an additional axis for ellipsoidal height.

**Comment by cmheazel** [comment]
From API Hackathon ER:
From GeoSeer
There should be a mandatory Bounding Box (BBOX) in WGS84, required for each collection, in
the OGC API - Common specification. This will facilitate discovery of spatial data - "WHERE"
being critical to such data. There are many thousands of "tree" datasets out there for instance,
how can a user otherwise know where the data is without this? Some wording to allow
exclusion for non-spatial datasets could be incorporated. This could be in addition to a native
BBOX defined by the extensions as necessary.

**Comment by cmheazel** [comment]
From API Hackathon ER:
(Hexagon) It was noted that there seems to be an opportunity for having more concepts in the Common API. Specifically, it seems that extent could be included.

**Comment by cmheazel** [comment]
From API Hackathon ER

( Spacebel) OpenSearch and OpenAPI Common convergence would benefit from a revision of OGC 10-032r8 to ensure that the geo:box, time:start and time:end can be combined in a single URL template with the actual HTTP query parameter names imposed by OpenAPI Common for temporal and geographical search.

**Comment by bradh** [comment]
Extent is very expensive to calculate for some vector sources (e.g. CSV or KML requires a full scan). It would be unfortunate if the Core / Common required bounding boxes for all of them.

Also, if the bounding box was required to be "tightly accurate", then formats like GeoPackage will require special handling - the list of contents (`gpkg_contents` table) only requires roughly indicative.

**Comment by cmheazel** [comment]
Bounding Box filtering is one of those functions which is pervasive in geospatial tools.  Folks expect it to be there.
On the other hand, there are times when it seems out of place.  What is the bounding box for a flight from Washington DC to Sydney?
We'll bring this issue up at the meeting in Banff.

**Comment by bradh** [comment]
I concur about the BBOX filtering (which could require a full table scan for some backend representations).

The task talks about having to declare a bounding box for the data set though (i.e. it would have to be available for every "collection"). I don't think Common should mandate that.

**Comment by jyutzler** [comment]
19-072 currently states the following:
```
The bounding box is provided as four or six numbers, depending
on whether the coordinate reference system includes a vertical
axis (height or depth):
• Lower left corner, coordinate axis 1
• Lower left corner, coordinate axis 2
• Lower left corner, coordinate axis 3 (optional)
• Upper right corner, coordinate axis 1
• Upper right corner, coordinate axis 2
• Upper right corner, coordinate axis 3 (optional)
```
I believe having an array of numbers is a terrible idea. Any time you have an array of numbers with non-obvious semantics, you run the risk of them being misinterpreted. We cannot assume that a developer will be looking at the standard to know the order. There is no reason to repeat the mistake GeoJSON made. Be explicit! There should be lowerLeft and upperRight elements with x, y, and optional z elements inside them. That way no one can mess them up.

For polar coordinates, a bounding box is irrelevant and shouldn't even be used. They are optional for a reason. They are still strongly recommended for all of the reasons mentioned elsewhere in this thread.

**Comment by jeffharrison** [comment]
Jeff Y,

Thank you for bringing this up. I can't believe we're having issues with this again... It's a fundamental capability for interoperability and needs to be explicit.

Best Regards,
Jeff

**Comment by cmheazel** [comment]
The bounding box parameter is defined in API-Common - Collections.  It is intended to be a simple filter to be applied to the extent element of the collectionInfo resource.

**Comment by chris-little** [comment]
I can't believe that geospatial didn't knock this nail squarely on the head a long time ago [insert bent nail/screw metaphor here]!
I would like to put in a plea to get away from the "lower left, upper right" terminology , as being too dependent on the traditional use case of looking at a 2D screen/map with a L-to-R writing system. If you look at the (transparent) screen from the other side, everything switches.
Please use "xmin, xmax" terminology which will work in multiple dimensions.

**Comment by Schpidi** [comment]
why not make the subset per axis explicit and use a syntax similar to what we use in wcs like `lat(min,max)` and `long(min,max)`?

**Comment by joanma747** [comment]
Please update the description of bbox to align it witht he last version of the OGC API Features part 2

* Lower left corner, coordinate axis 1
                * Lower left corner, coordinate axis 2
                * Minimum value, coordinate axis 3 (optional)
                * Upper right corner, coordinate axis 1
                * Upper right corner, coordinate axis 2
                * Maximum value, coordinate axis 3 (optional)

**Comment by chris-little** [comment]
@joanma747 Why only 3 dimensions/6 coordinates? Why not 4 and 8 for time bound 3D resources?

**Comment by cmheazel** [comment]
Suggested changes have been made. 
Also see issue #164

**Comment by ghobona** [comment]
@cmheazel I will add the resolution of this issue to the OAB report. Please keep the **Cross-SWG Discussion** label on the issue.

**Comment by jerstlouis** [comment]
Suggesting Common adopts subset as a common trimming parameter instead in #167.

On the separate issue of the Geospatial data exten in the collection description resource,
@bradh I would argue that services should always provide an extent even if not required to do so, because finding data by area of interest would be a very common use case, and not having an extent would severely affect the data's findability and discoverability. From the server's perspective, can't that expensive scanning be cached? A server wishing to be efficient would also unlikely use KML or CSV as a backend for large datasets.

**Comment by m-mohr** [comment]
I'd be in favor to keep it as is for backward compatibility. It was argued in other issues that backward compatibility should remain with Features (and standards built on top of it) as far as possible, so I think this applies here, too. Also, I think subset as term is not very clear if you don't know Coverages. BBox is very clear IMHO.

**Comment by jerstlouis** [comment]
@m-mohr RE: Features, BBOX would retain its intersection meaning, whereas subset could potentially be supported as an optional conformance class allowing to 'clip' the features.

The meaning of `&subset=Lat(lat1:lat2),Long(lon1:lon2)` is much clearer to me than `&bbox=lon1,lat1,lon2,lat2` where I have no idea what each of the 4 number is.

**Comment by m-mohr** [comment]
Okay, fine for me as optional addition with a separate conformance class.

**Comment by ghobona** [comment]
@jerstlouis The proposal to introduce 'subset' is separate from the discussion in this GitHub Issue #43.

The proposal to introduce 'subset' should be discussed in Issue https://github.com/opengeospatial/oapi_common/issues/164

Since there is no objection to keeping BBOX, this Issue #43 should be closed.

**Comment by jerstlouis** [comment]
@ghobona #164 is a different topic altogether:

> Add explanatory text to API-Common Part 2 about the purpose and limitations of the bbox parameter.

and in fact I disagree with a few of those things said in that issue's one comment.

I propose to introduce `subset` in Common in https://github.com/opengeospatial/oapi_common/issues/167

Although `bbox` may remain for intersecting features in _Features_, and potentially for usage with the `/collections` resource, it should be discussed whether `bbox` should be kept as a query parameter for sub-setting data, e.g. as used in _Maps_, rather than adopting subset instead.

**Comment by chris-little** [comment]
@jerstlouis I disagree with overloading BBOX. We use it in EDR API, completely compatible with Features API, to select collections of interest. The subsetting is then part of the selection/query. Sensible subsetting may need knowledge of the server data's CRS. Currently the features approach leaves BBOX as CRS84 - straightforward.

**Comment by cmheazel** [comment]
So Issue #167 adds a subset parameter, Issue #164 provides the text explaining the difference between the two, and issue #43 can be closed.

**Comment by ghobona** [comment]
**2020-09-15 OGC API Cross Cutting Issues session during OGC Member Meeting**

See the related resolution at https://github.com/opengeospatial/oapi_common/issues/164#issuecomment-693477644

**Comment by cmheazel** [comment]
This issue has been subsumed by issue #164.
