### ISSUE TITLE
Title and Description Metadata

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#50]
From the API Hackathon ER:
The "Title", and "Description", fields are both optional in the Common, Features and Map Tiles
specifications. These fields should be mandatory. If they are not, they will not be there for many
services and that will make them considerably less discoverable. It will also significantly reduce
usability with desktop GIS (imagine selecting a feature collection when none of them have
these…).

**Comment by cmheazel** [comment]
Well known metadata fields are an enabler of discovery.  One option is to create an OGC profile of OpenAPI which will define additional fields for the /info object.  OpenAPI is designed for this type of extensibility so compatibility with non-OGC tools should not be a problem.

**Comment by joanma747** [comment]
It is responsability of the publisher of the metadata to make metadata complete and data discoverable. The fact that Title is mandatory will not improve metadata as users can always can trick the system and provide "Layer 1" as title. 
I vote to close this issue.

**Comment by m-mohr** [comment]
I vote to make them required. It at least gives guidance to the implementer that the fields are important to fill.

**Comment by bradh** [comment]
Yes to title. I'd prefer to see description optional, because it makes it easier to distinguish between "I've got a meaningful description" and "I just replicated the title because that is all I had". 

Iff its required for interoperability, then it should be required. Otherwise we should provide mechanism and leave policy to any profiles / implementation guides.

**Comment by cmheazel** [comment]
Title and description are already included in the JSON Schema for the landing page. This schema has been updated to make the title property required.
Is anything else needed?

**Comment by joanma747** [comment]
In 2020-11-30 telco we resolve the same that in https://github.com/opengeospatial/oapi_common/issues/174: we include them in the schema and a small text in the document describing them next to "attribution".

**Comment by cportele** [comment]
I understand the motivation for making "title" required, but I still think it is unnecessary as it not needed for clients to use the API. Yes, there should be a useful title, but this is more a recommendation or good practice than a requirement.

**Comment by jerstlouis** [comment]
It may be useful to make both optional, but provide clear guidance that `title` is more essential than `description`.

**Comment by cmheazel** [comment]
Updated JSON schema and YAML for the landing page. Title is no longer required. Added description "While a title is not required, implementors are strongly advised to include one."

**Comment by cmheazel** [comment]
February 1 - missed mention that tile is required in section 8.2.1. Correct.
Close once change has been made. NOTUC

**Comment by cmheazel** [comment]
Done
