### ISSUE TITLE
Metadata URLs

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-common#51]
From the API Hackathon ER:
From GeoSeer:
Metadata URLs should be included too. While GeoSeer were not big fans of external metadata
documents, many large organizations find them extremely important and they are used a fair
percentage on current services. A consistent way to specify them would make access to this
information automatically easier.

**Comment by joanma747** [comment]
That is possible today in collections. You have to add a link in the metadata of the collection with rel=via (https://tools.ietf.org/html/rfc4287#section-4.2.7.2)

 {
      "href": "http://schemas.example.org/1.0/md.xml",
      "rel": "via",
      "type": "application/xml",
      "title": "Metadata in ISO19115 for Acme Corporation dataset data"
    }

I would like to close this issue.

**Comment by jyutzler** [comment]
Huh? From the link you provided, "via" is for sources.

> The value "via" signifies that the IRI in the value of the href attribute identifies a resource that is the source of the information provided in the containing element.

That is not a metadata document. In OGC API-Styles, we're using a link with a "describedBy" rel. See https://github.com/opengeospatial/ogcapi-styles/blob/master/standard/clause_7_styles-api.adoc#user-content-req_core_styles-success Req2F.

**Comment by joanma747** [comment]
I really do not know. In the OWS Context group they convinced my it was "via". In some OGC API features examples (old?) describedBy was used for data models in xsd.

I'm try but I'm always confused with rels.

**Comment by joanma747** [comment]
There are two ways of adding metadata:
* A full metadata record can be linked to the collection
* Some metadata entries directly in the collection

* For the first we need a relation type (via? about?)
* For the second we need to define a list of possible fields

**Comment by ghobona** [comment]
2020-09-29 OGC API Sprint

The sprint participants recommended that we define a specific relation type to link to metadata documents which could be used to link to standard metadata types such as ISO 19115 , properly identified by media types. Possibly also include additional fields. Both of these could be done at both the dataset and at the collection level. This should be specified in  OGC API - Common - Part 2: Geospatial Data.

We could use the '[publication](https://www.iana.org/assignments/link-relations/link-relations.xhtml)' relation type from IANA for the dataset or collection.

**Comment by ghobona** [comment]
Example use case is at https://github.com/opengeospatial/OGC-API-Sprint-September-2020/issues/11

**Comment by joanma747** [comment]
We agreed this solution in 2020-11-02 telco:

We are not able to find the right "word" in the iana (https://www.iana.org/assignments/link-relations/link-relations.xhtml). we see that describeBy can be used both for metadata an schemas and we cannot redefine this.

So we see the need for registering something in our OGC-NA. The proposal is
"data-meta": "Identifies general metadata for the context (dataset or collection) that is primarily intended for consumption by machines."
data-meta is NOT intended for schemas. data-meta can link to ISO 19115, DCAT, FGDC, Dublin core files. MediaType will not help in differentiate them. A possible to use _content negotiation by profile_ to select one of them. Providers are encouraged to use this link if they have a metadata document is available.

We will work on finding the right one for schemas in another issue/time.

**Comment by cmheazel** [comment]
The "data-meta" relation has been added to API-Common Part 1.

**Comment by cmheazel** [comment]
"data-meta" seems to have dropped out of Part 1.  This has been fixed.  "data-meta" has been added to Part 2.
