### ISSUE TITLE
Support for a Global Grid System (Extension?)

### ISSUE THREAD

**Issue by uvoges** [opengeospatial/ogcapi-common#6]
I guess it would be beneficial to have support for an axis representing a global Grid System for navigation through the resources. Maybe in an extension?
We use e.g. in different projects the Equi7Grid (https://github.com/TUW-GEO/Equi7Grid).

**Comment by jerstlouis** [comment]
The upcoming Tile Matrix Set 1.0 standard now supports varying width matrix descriptions which is very handy for this sort of things. Two examples of global grids that can now be described with this are the GNOSIS Global Grid ( http://docs.opengeospatial.org/per/17-041.html#_global_gnosis_tiling_scheme_adapted_to_polar_regions ) and the CDB Tiling Grid.

Also, my opinion is that any data partitioning/exchange mechanism should be usable through extension points as long as they are agreed upon by client & server (e.g. tiles, DGGS cells, subsetting...), so any Grid System should definitely be possible.

**Comment by jerstlouis** [comment]
Closing this issue as the use case is covered by OGC API - DGGS.
